name: MCSH
version: 2.8.1
main: com.coritan.mcsh.bukkit.MCSHBukkit
softdepend:
- ProtocolLib
- floodgate
author: https://coritan.com
description: MCSH IP parsing capabilities for Bukkit/Spigot/Paper
api-version: 1.16
